using System.Reflection;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

// General Information about an assembly is controlled through the following
//  set of attr ib utes. Change t hese attribute values to modify the information                                   
                        

                 
                                    

          
                                      
           
                          
                                                     
           
                

                  

                             

                      
                            
                  

                
                                      

                            
                  
                           
                                                                            
                                 
                                      
                                                                       
              
                  
                  
                    
                  
                  
                  
                     
                                 
                         
                   
                                       
                              
                                            
                                                                                          
                                  
                                                                                           
                  
                  
                    
                  
                  
                         
                             
                                       
                   
                                  
                                           
                                          
                                        
                                           
                                        
                                                
                                                              
                             
                                        
                  
                  
                    
                  
                  
                  
                  
                  
                             
                             
                           
                                                   
                                   
                                 
                   
                                                         
                                        
                                                                                
                                                              
                                                                                    
                                                        
                            
                                  
                            
                                  
                            
                                                     
                                
                              
                                
                                                      
                                                                        
                                        
                              
                                   
                              
                              
                              
                                                                                       
                                                                                  
                                                                      
                                         
                                                              
                                      
                                                                              
                                             
                  
                  
                    
                  
                  
                  
                       
                       
                                         
                           
                       
                       
                   
                                                                                       
                                                                        
                                                                 
                                            
                                                                     
                                            
                                                                                                                                   
                              
                                                     
                                                          
                                  
                                                                              
                                                                 
                      
                          
                                        
                  
                  
                    
                  
                  
                  
                  
                  
                  
                                                         
                         
                                 
                   
                                         
                                            
                                        
                                                                                          
                                                 
                                             
                                                               
                                                     
                                                         
                                                       
                                                
                                                                                                                    
                  
                  
                    
                  
                  
                  
                  
                  
                           
                           
                                                                 
                             
                           
                   
                                                                           
                                     
                                                                              
                               
                                                                                                          
                                
                                                   
                                       
                                     
                                              
                                                
                                        
                                                         
                                                                                     
                                             
                                                                                                           
                                                     
                                             
                                                                     
                                                                   
                      
                      
                                                     
                                      
              
                  
                  
                    
                  
                  
                         
                         
                                 
                             
                                     
                       
                   
                         
                                                                           
                          
                                    
                                    
                                    
                                   
                            
                                                                                                                   
                                                                                       
                              
                                                                                                
                                           
                                              
                                               
                         
                              
                                            
                            //  a ss oc i ated with a n a ssembly.              
                                 
                        
                                         
                
                          
                                       
             
                  
                  
                    
                  
                  
                  
                                         
                             
                                       
                   
                                                
                                  
                                  
                                  
                                            
                                                                 
                                              
                                      
                                                            
                              
                                      
                                    
                                                 
                                                  
                                 
                                    
                                                       
                                                                                   
                  
                  
                    
                  
                  
                  
                                         
                                         
                           
                       
                                                           
                       
                       
                       
                           
                   
                                                                                       
                                  
                                                    
                                                                                            
                                        
                                  
                                              
                                  
                                        
                                                            
                                                      
                                     
                              
                                                      
                                                                          
                                                                                                            
                              
                                   
                                         
                                            
                                           
                                                       
                                                                                                                                                                  
                               
                                                                
                                               
                                                                      
                                                                                                                       
        
              
              
                
              
                         
                   
                   
                   
                                                       
               
                                                  
                                                     
                                                                    
                                                                                                                   

[assembly: AssemblyTitle("Repository")]
[assembly: AssemblyDescription("")]
[assembly: AssemblyConfiguration("")]
[assembly: AssemblyCompany("")]
[assembly: AssemblyProduct("Repository")]
[assembly: AssemblyCopyright("Copyright ©  2020")]
[assembly: AssemblyTrademark("")]
[assembly: AssemblyCulture("")]

// Setting ComVisible to false makes the types in this assembly not visible
// to COM components.  If you need to access a type in this assembly from
// COM, set the ComVisible attribute to true on that type.
[assembly: ComVisible(false)]

// The following GUID is for the ID of the typelib if this project is exposed to COM
[assembly: Guid("b5670074-9320-477d-944c-7f705cc3b294")]

// Version information for an assembly consists of the following four values:
//
//      Major Version
//      Minor Version
//      Build Number
//      Revision
//
// You can specify all the values or you can default the Build and Revision Numbers
// by using the '*' as shown below:
// [assembly: AssemblyVersion("1.0.*")]
[assembly: AssemblyVersion("1.0.0.0")]
[assembly: AssemblyFileVersion("1.0.0.0")]
