// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WEBloco.Infrastructure.Data.Context;

namespace WEBloco.Infrastructure.Data.Migrations
{
    [DbContext(typeof(HeroiContext))]
    partial class HeroiContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WEBloco.Domain.Model.Entities.Heroi", b =>
                {
                    b.Property<int>("HeroiId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Codinome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Lancamento")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Poder")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("HeroiId");

                    b.ToTable("Heroi");
                });

            modelBuilder.Entity("WEBloco.Domain.Model.Entities.Imagem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("FotoUri")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("HeroiId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("HeroiId");

                    b.ToTable("Imagem");
                });

            modelBuilder.Entity("WEBloco.Domain.Model.Entities.Imagem", b =>
                {
                    b.HasOne("WEBloco.Domain.Model.Entities.Heroi", "Heroi")
                        .WithMany("Imagens")
                        .HasForeignKey("HeroiId");
                });
#pragma warning restore 612, 618
        }
    }
}
